server {
    listen 8080;

    # Serve the frontend app
    root /home/option-trader/frontend/dist/option-trader-dashboard;
    index index.html;

    # Serve state.json from cache folder
    location /state.json {
        alias /home/option-trader/shared/state.json;
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin *;
        add_header Content-Type "application/json";
    }

    # Serve supervisor_state.json from cache folder
    location /supervisor_state.json {
        alias /home/option-trader/shared/supervisor_state.json;
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin *;
        add_header Content-Type "application/json";
    }

    # Serve frontend for everything else
    location / {
        try_files $uri $uri/ /index.html;
    }
}