[loggers]
keys=root, option_safeguard, trading_bot

[handlers]
keys=consoleHandler, fileHandler

[formatters]
keys=dummyFormatter, fileFormatter

[logger_root]
level=INFO
handlers=consoleHandler, fileHandler

[logger_option_safeguard]
level=INFO
handlers=consoleHandler, fileHandler
qualname=option_safeguard
propagate=0

[logger_trading_bot]
level=INFO
handlers=consoleHandler, fileHandler
qualname=trading_bot
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=dummyFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=fileFormatter
args=('%(logfilename)s', 'a', 'utf-8')

[formatter_dummyFormatter]
format=%(message)s

[formatter_fileFormatter]
format=[%(levelname)s] %(asctime)s - %(name)s: %(message)s
datefmt=%Y-%m-%d %H:%M:%S